FROM rapidsai/rapidsai:0.13-cuda10.1-base-ubuntu18.04-py3.7
ARG WORK_DIR=/lab

# Install conda dependencies
COPY environment.yml /tmp/
RUN conda env update -n rapids --file /tmp/environment.yml
RUN PATH=/conda/envs/rapids/bin/:$PATH bash -c 'jupyter labextension install dask-labextension'

# Install test/ci dependencies
COPY environment.ci.yml /tmp/
RUN conda env update -n rapids --file /tmp/environment.ci.yml

# Install pysnptools separately (does not work as pip install with conda env update)
RUN apt-get update && apt-get install -y g++
RUN /conda/envs/rapids/bin/pip install --no-cache-dir pysnptools==0.4.11

# PLINK installation
# Adapted from: https://github.com/GELOG/plink/blob/master/plink-2.0-bin/docker/Dockerfile
# Download is from https://www.cog-genomics.org/plink2 (version = 1.90 beta)
RUN apt-get install -y unzip
RUN wget -q http://s3.amazonaws.com/plink1-assets/plink_linux_x86_64_20200107.zip && \
  unzip plink_linux_x86_64_20200107.zip -d /usr/local/plink && \
  rm plink_linux_x86_64_20200107.zip
RUN echo 'export PLINK_HOME=/usr/local/plink' >> ~/.bashrc
RUN echo 'export PATH=/usr/local/plink:$PATH' >> ~/.bashrc
ENV PATH /usr/local/plink:$PATH
ENV PLINK_HOME /usr/local/plink

# VS code server installation
RUN wget -q https://github.com/cdr/code-server/releases/download/3.2.0/code-server-3.2.0-linux-x86_64.tar.gz && \
    tar -xf code-server-3.2.0-linux-x86_64.tar.gz && \
    rm code-server-3.2.0-linux-x86_64.tar.gz && \
    chmod a+x code-server-3.2.0-linux-x86_64/code-server
RUN ln -s $PWD/code-server-3.2.0-linux-x86_64/code-server /usr/local/bin/code-server
RUN code-server --install-extension ms-python.python && \
    code-server --install-extension njpwerner.autodocstring

# Dask labextension config 
COPY labextension.yaml $HOME/.config/dask/labextension.yaml

RUN mkdir -p $WORK_DIR/data $WORK_DIR/repos $WORK_DIR/logs
WORKDIR $WORK_DIR

COPY dev.code-workspace ./
COPY init.sh ./

# Add helpful environment variables
ENV WORK_DIR $WORK_DIR
ENV DATA_DIR $WORK_DIR/data
ENV LOGS_DIR $WORK_DIR/logs
ENV REPO_DIR $WORK_DIR/repos/gwas-analysis
ENV NB_DIR $REPO_DIR/notebooks
ENV JUPYTERLAB_PORT 8888
ENV CODESERVER_PORT 8887
ENV SHELL /bin/bash

# As a temporary workaround until this project has its own repo, put the conda on the PYTHONPATH for the environment
RUN echo "$WORK_DIR/repos/gwas-analysis/notebooks/platform/xarray" >> /conda/envs/rapids/lib/python3.7/site-packages/local.pth

CMD /bin/bash init.sh && /bin/bash
